### ISSUE TITLE
Expression template and colorization cannot be set at the same time

### ISSUE THREAD

**Issue by PatrikBak** [serilog/serilog-expressions#61] opened 2022-01-22 16:55 UTC
I have this 

```
"Serilog": {
  "MinimumLevel": "Information",
  "WriteTo": [
    {
      "Name": "Console",
      "Args": {
        "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Literate, Serilog.Sinks.Console",
        "formatter": {
          "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
          "template": "a[{@t:HH:mm:ss}] [{@l:u3}] {#each name, value in Rest(true)}[{name}: {value}] {#end}{@m}\n{@x}"
        }
      }
    }
  ]
}
```

(1) If I use this, the theme seems to work, but the template is silently ignored.
(2) If I remove "theme", the template will work, but my output won't be colorized at all (running through Visual Studio 2019 and CTRL+F5)

How do I make them both work?

My versions:

```
<PackageReference Include="Serilog.Extensions.Logging" Version="3.1.0" />
<PackageReference Include="Serilog.Filters.Expressions" Version="2.1.0" />
<PackageReference Include="Serilog.Expressions" Version="3.2.1" />
<PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
```

**Comment by PatrikBak** [comment] 2022-01-22 18:24
In the end, I used this

```
public class ExpressionTemplateHack : ExpressionTemplate
{
    public ExpressionTemplateHack(string template)
        : base(template, theme: TemplateTheme.Literate)
    {
    }
}
```

and

```
formatter = {
    type = "Namespace.ExpressionTemplateHack, MyAssembly",
    template = "[{@t:HH:mm:ss}] [{@l:u3}] {#each name, value in Rest(true)}[{name}: {value}] {#end}{@m}\n{@x}"
}
```

I'm just glad to have some colors back and still be able to use a settings file :)

**Comment by nblumhardt** [comment] 2022-01-23 22:45
Thanks for reporting this; it's a duplicate of https://github.com/serilog/serilog-settings-configuration/issues/287, which is fixed in the latest `-dev` version of Serilog.Settings.Configuration.

**Closed by nblumhardt** 2022-01-23 22:45 UTC
